# Schema for the configuration files of the moodle.course_settings.

moodle.course_settings:
  type: config_object
  label: 'Course settings'
  mapping:
    window_target:
      type: string
      label: 'The course Link target attribute.'