# Schema for the configuration files of the moodle.connector_settings.

moodle.connector_settings:
  type: config_object
  label: 'Connector settings'
  mapping:
    url:
      type: string
      label: 'The moodle url'
    database_connection_key:
      type: string
      label: 'The moodle database connection key'
